int menu();
void add(struct Series**);
void print(struct Series*, int);
void deleteEnter(struct Series*);
void rightRegister(struct Series*);
void del(struct Series**);
void search(struct Series*);
void clear(struct Series**);
void writeTextFile(struct Series*);
void write(struct Series*);
void writeBinFile(struct Series*);
void read(struct Series**);
void readTextFile(struct Series**);
void readBinFile(struct Series**);
void reverse(struct Series**);