int menu();
void add(struct Series**, struct Series**);
void print(struct Series*, int);
void printLine();
void deleteEnter(struct Series*);
void rightRegister(struct Series*);
void del(struct Series**, struct Series**);
void search(struct Series*);
void clear(struct Series**, struct Series**);
void writeTextFile(struct Series*);
void write(struct Series*);
void writeBinFile(struct Series*);
void read(struct Series**, struct Series**);
void readTextFile(struct Series**, struct Series**);
void readBinFile(struct Series**, struct Series**);