struct TheGame* add(struct TheGame*, int, int);
void show(struct TheGame*, int);
void printGames(struct TheGame*, int);
void change(struct TheGame*, int);
void changeOneGame(struct TheGame*, int);
void partChange(struct TheGame*, int);
int inputValidationInt();
float inputValidationFloat();
void line();
void hat();
int menu();
int correctChoice(int);
void search(struct TheGame*, int);
void searchByGivenParam(struct TheGame*, int);
void particalSearch(struct TheGame*, int);
void findCharNumber(struct TheGame*, int, int);
struct TheGame* del(struct TheGame*, int);
struct TheGame* delExact(struct TheGame*, int, int);
void sortFromMax(struct TheGame*, int);
void sortFromMin(struct TheGame*, int);
void sort(struct TheGame*, int);